### ISSUE TITLE
box multi in travis CI has an exceedingly impressive output

### ISSUE THREAD

**Issue by Xe** [erikh/box#122]
https://travis-ci.org/PonyvilleFM/aura/builds/194235237#L1

run like this: https://github.com/PonyvilleFM/aura/commit/90467a59da4d3f8b105d5f8ee406473155ef798e

**Comment by erikh** [comment]
Ok for some reason you're getting a tty which is causing the issue. Try
passing --no-tty or optionally remove the -t from your docker commands if
you're doing that. Should fix your other colorIzed outputs too.

**Comment by erikh** [comment]
Oh. I see it now. I'll try to put in a patch this week.

For now, run without tty mode, that's a temporary fix.

**Comment by Xe** [comment]
Even without TTY mode it's still enough output that it's a blocker for using it. I'll re-enable `box multi` when this patch is made.

**Comment by erikh** [comment]
Oof. Ok. Sorry!



On Mon, Jan 23, 2017 at 2:15 PM, Christine Dodrill <notifications@github.com
