### ISSUE TITLE
Create a Homebrew Formula

### ISSUE THREAD

**Issue by Nikkau** [erikh/box#123]
Hi,

I just discovered box and I love it, to show it to my friends easily, I just create a Formula for Homebrew, the OSX package tools.

Now you can install the last version of box with `brew install nikkau/tools/box`.

Maybe you can create an "official" Homerew Tap for box?

It's easy : http://docs.brew.sh/How-to-Create-and-Maintain-a-Tap.html
And you can C/C my Formula to save time : https://github.com/Nikkau/homebrew-tools/blob/master/Formula/box.rb

**Comment by erikh** [comment]
Awesome! Thank you very much!

I will leave this open until I finish this work. I'm very busy this week so
it'll probably be sometime after that. Thanks for putting this together!

**Comment by erikh** [comment]
I've done this work over at github.com/erikh/homebrew-box.  Thanks so much!

**Comment by Nikkau** [comment]
Great.

BTW, by experience, few MacOS users know how custom taps work, you may get more users by directly showing the `brew install erikh/box/box` in the box's readme I think.

**Comment by erikh** [comment]
Ok, I'll do that.

**Comment by erikh** [comment]
done!
