### ISSUE TITLE
label verb

### ISSUE THREAD

**Issue by errordeveloper** [erikh/box#144]
Would be great to be able to set labels, e.g. `org.label-schema.vcs-url` and `org.label-schema.vcs-ref` are quite useful for implementing CD etc.

One options to consider is that labels may be passed to `tag`, as you might want to associate different sets of labels with different tags. It'd make a lot of sense with how we can already set tags as we progress through a build plan.

```Ruby
def build_base_image
end

def enable feature
end

build_base_image

rev = getenv("GIT_COMMIT")
feature = getenv("BUILD_FEATURES").slip(",")

labels = {
  "org.label-schema.vcs-ref" => rev
}

tag "foo:minimal-#{rev}", with_labels: labels

features.each do |feature|
  enable feature
  labels["org.example.features.#{feature}"] = true
end

tag "foo:full-#{rev}", with_labels: labels
```

**Comment by erikh** [comment]
I like this, but should there be an actual label verb on top of the
extensions to the tag verb?

On Tue, Feb 14, 2017 at 8:23 AM, Ilya Dmitrichenko <notifications@github.com

**Comment by errordeveloper** [comment]
I think actual verb would be a good start, some users might just want to declare labels at the top.

**Comment by erikh** [comment]
Ok, I'll try to get started on this soon.

On Thu, Feb 16, 2017 at 1:51 AM, Ilya Dmitrichenko <notifications@github.com
