### ISSUE TITLE
flaky errors with `debug`

### ISSUE THREAD

**Issue by errordeveloper** [erikh/box#54]
When using `debug` command, I see this once in a while:
```
+++ Run Error: read unix @->/var/run/docker.sock: use of closed network connection

!!! Error: Could not remove intermediate container "11f3be63b86811762ceb4084c2344816364d78a1afd59b7d129f0def2c3c222e": Error response from daemon: No such container: 11f3be63b86811762ceb4084c2344816364d78a1afd59b7d129f0def2c3c222e
make: *** [wordpress-import] Error 1
```

Sometimes it only complains about the socket and doesn't complain about removing intermediate container:
```
+++ Run Error: write unix @->/var/run/docker.sock: use of closed network connection

+++ Tagged: wordpress-import

+++ Eval Response: sha256:1178c61d6a163aff1ca54b3b22fc2f134e75474c9ac3e97cd414f7bb38599482
+++ Finish: 1178c61d6a163aff1ca54b3b22fc2f134e75474c9ac3e97cd414f7bb38599482
```

It happens either before I get the debug shell, or once I exit it.

**Comment by erikh** [comment]
This is fixed in latest master now. Give it a shot if you get time.

**Comment by errordeveloper** [comment]
@erikh it'd be handy if you could publish an image...

**Comment by errordeveloper** [comment]
I wonder if `write unix @->/var/run/docker.sock: use of closed network connection` could be somehow related to Docker for Mac... I'm gonna try using `-v /var/run:/var/run` also, in case the socket gets nuked somehow and bind-mount breaks.

**Comment by erikh** [comment]
I was seeing it on linux too.

**Comment by erikh** [comment]
@errordeveloper try erikh/box:master, I'm going to start publishing this on push once I have time to set it up.

**Comment by errordeveloper** [comment]
It seems to work much better with ` erikh/box@sha256:2e25cc0af3935b535308b6da8fddc13f206eeca1f81aa92a493876bfd2a87b93`, thank you!

**Comment by erikh** [comment]
awesome. I'm going to close this then.
